### ISSUE TITLE
Thresholded Ground Distance

### ISSUE THREAD

**Issue by ksanjeevan** [wmayner/pyemd#23]
Hi, the ICCV paper makes use of a thresholded ground distance d_t(a,b) = min(t, d(a,b)) to better the time complexity, does this need to be reflected in the distance_matrix before passing it as an argument? If so what value do we set for the threshold?

**Comment by wmayner** [comment]
Yes, if you set a threshold it must be reflected in the distance matrix—there's nothing in the code about thresholds. It's mentioned because it's one of the main points in their paper. As for the value, I don't think there's a meaningful notion of a good threshold value without reference to a particular application. I would recommend experimenting with different values; ideally you'd use the smallest value that doesn't negatively impact accuracy, whatever that might mean in your case.

**Comment by wmayner** [comment]
You don't need to. The threshold for any distance matrix `D` is just `max(D)`, so their code simply uses that.
