### ISSUE TITLE
about the input

### ISSUE THREAD

**Issue by edwinZeng** [wmayner/pyemd#6]
Thanks for providing a wrapper to the emd calculation in python:

what is the meaning of the signature? as far as i know, emd basically calculate a distance between two distribution. I guess that the distance_matrix as input is the ground distance [e.g. pairwise L2 distance], but what does the signature stands for? is it considering the weight in the historgram? 

How about the N? looks like that it is a total number of bins in both histogram.

Thanks for your time in answering the question.
Edwin

**Comment by wmayner** [comment]
Hi Edwin,

Glad you're finding it useful! *Signature*, *histogram*, and *distribution* are all synonyms here. And yes, *N* is the number of bins. Hope that helps.

**Comment by edwinZeng** [comment]
hi,

         let say that the histogram is calculated from dynamic clustering
such that the number of clusters is not fixed. suppose for dataset 1, we
generate a histogram of.5 bins. we also generate a histogram with 7 bins
for 2nd dataset. we can build a histogram based on the counting. suppose we
can also calculate the pairwise ground distance using the.respective
clustering center, which is a 5x7 matrix. In this case, how i can
reformulate my problem in order to use the code?

thanks
Edwin
2015/12/5 下午10:47 於 "Will Mayner" <notifications@github.com> 寫道：

**Comment by wmayner** [comment]
Hi,

Unless I've misunderstood something, I believe you can achieve what you want by simply adding empty bins to the shorter histogram so that they're the same length. The distance from the empty bins can then be assigned to be larger than any other distance.

Under those conditions, no mass will ever be moved from or to the “padding” bins, so the computed distance will effectively be between the 5-bin and 7-bin histograms, whatever order you compare them in.
